using Apprendi.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Apprendi.Infrastructure.Persistence.Configurations
{
    public class TimeZoneConfiguration : IEntityTypeConfiguration<Domain.Entities.TimeZone>
    {
        public void Configure(EntityTypeBuilder<Domain.Entities.TimeZone> builder)
        {
            builder
                .Ignore(timeZone => timeZone.Name);

            builder
                .HasKey(timeZone => timeZone.Id);

            builder
                .Property(timeZone => timeZone.Id)
                .HasMaxLength(35)
                .IsRequired();

            builder
                .Property(timeZone => timeZone.CountryId)
                .HasMaxLength(2)
                .IsRequired();

            builder
                .HasOne(timeZone => timeZone.Country)
                .WithMany(country => country.TimeZones)
                .HasForeignKey(timeZone => timeZone.CountryId)
                .OnDelete(DeleteBehavior.Restrict); 

            builder
                .HasIndex(timeZone => timeZone.CountryId);

            builder
                .HasData(GetSeedData());
        }

        public static IEnumerable<Domain.Entities.TimeZone> GetSeedData()
        {
            yield return new Domain.Entities.TimeZone { Id = "Africa/Abidjan", CountryId = "CI" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Accra", CountryId = "GH" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Addis_Ababa", CountryId = "ET" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Algiers", CountryId = "DZ" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Bamako", CountryId = "ML" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Bangui", CountryId = "CF" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Banjul", CountryId = "GM" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Bissau", CountryId = "GW" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Blantyre", CountryId = "MW" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Brazzaville", CountryId = "CG" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Bujumbura", CountryId = "BI" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Cairo", CountryId = "EG" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Casablanca", CountryId = "MA" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Ceuta", CountryId = "ES" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Conakry", CountryId = "GN" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Dakar", CountryId = "SN" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Dar_es_Salaam", CountryId = "TZ" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Djibouti", CountryId = "DJ" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Douala", CountryId = "CM" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/El_Aaiun", CountryId = "EH" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Freetown", CountryId = "SL" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Gaborone", CountryId = "BW" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Harare", CountryId = "ZW" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Johannesburg", CountryId = "ZA" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Juba", CountryId = "SS" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Kampala", CountryId = "UG" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Khartoum", CountryId = "SD" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Kigali", CountryId = "RW" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Kinshasa", CountryId = "CD" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Lagos", CountryId = "NG" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Libreville", CountryId = "GA" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Lome", CountryId = "TG" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Luanda", CountryId = "AO" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Lubumbashi", CountryId = "CD" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Lusaka", CountryId = "ZM" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Malabo", CountryId = "GQ" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Maputo", CountryId = "MZ" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Maseru", CountryId = "LS" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Mbabane", CountryId = "SZ" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Mogadishu", CountryId = "SO" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Monrovia", CountryId = "LR" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Nairobi", CountryId = "KE" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Ndjamena", CountryId = "TD" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Niamey", CountryId = "NE" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Nouakchott", CountryId = "MR" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Ouagadougou", CountryId = "BF" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Porto-Novo", CountryId = "BJ" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Sao_Tome", CountryId = "ST" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Tripoli", CountryId = "LY" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Tunis", CountryId = "TN" };
            yield return new Domain.Entities.TimeZone { Id = "Africa/Windhoek", CountryId = "NA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Adak", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/Anchorage", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/Anguilla", CountryId = "AI" };
            yield return new Domain.Entities.TimeZone { Id = "America/Antigua", CountryId = "AG" };
            yield return new Domain.Entities.TimeZone { Id = "America/Araguaina", CountryId = "BR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Argentina/La_Rioja", CountryId = "AR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Argentina/Rio_Gallegos", CountryId = "AR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Argentina/Salta", CountryId = "AR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Argentina/San_Juan", CountryId = "AR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Argentina/San_Luis", CountryId = "AR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Argentina/Tucuman", CountryId = "AR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Argentina/Ushuaia", CountryId = "AR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Aruba", CountryId = "AW" };
            yield return new Domain.Entities.TimeZone { Id = "America/Asuncion", CountryId = "PY" };
            yield return new Domain.Entities.TimeZone { Id = "America/Bahia", CountryId = "BR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Bahia_Banderas", CountryId = "MX" };
            yield return new Domain.Entities.TimeZone { Id = "America/Barbados", CountryId = "BB" };
            yield return new Domain.Entities.TimeZone { Id = "America/Belem", CountryId = "BR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Belize", CountryId = "BZ" };
            yield return new Domain.Entities.TimeZone { Id = "America/Blanc-Sablon", CountryId = "CA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Boa_Vista", CountryId = "BR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Bogota", CountryId = "CO" };
            yield return new Domain.Entities.TimeZone { Id = "America/Boise", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/Cambridge_Bay", CountryId = "CA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Campo_Grande", CountryId = "BR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Cancun", CountryId = "MX" };
            yield return new Domain.Entities.TimeZone { Id = "America/Caracas", CountryId = "VE" };
            yield return new Domain.Entities.TimeZone { Id = "America/Cayenne", CountryId = "GF" };
            yield return new Domain.Entities.TimeZone { Id = "America/Cayman", CountryId = "KY" };
            yield return new Domain.Entities.TimeZone { Id = "America/Chicago", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/Chihuahua", CountryId = "MX" };
            yield return new Domain.Entities.TimeZone { Id = "America/Costa_Rica", CountryId = "CR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Creston", CountryId = "CA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Cuiaba", CountryId = "BR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Curacao", CountryId = "CW" };
            yield return new Domain.Entities.TimeZone { Id = "America/Danmarkshavn", CountryId = "GL" };
            yield return new Domain.Entities.TimeZone { Id = "America/Dawson", CountryId = "CA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Dawson_Creek", CountryId = "CA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Denver", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/Detroit", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/Dominica", CountryId = "DM" };
            yield return new Domain.Entities.TimeZone { Id = "America/Edmonton", CountryId = "CA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Eirunepe", CountryId = "BR" };
            yield return new Domain.Entities.TimeZone { Id = "America/El_Salvador", CountryId = "SV" };
            yield return new Domain.Entities.TimeZone { Id = "America/Fort_Nelson", CountryId = "CA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Fortaleza", CountryId = "BR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Glace_Bay", CountryId = "CA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Goose_Bay", CountryId = "CA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Grand_Turk", CountryId = "TC" };
            yield return new Domain.Entities.TimeZone { Id = "America/Grenada", CountryId = "GD" };
            yield return new Domain.Entities.TimeZone { Id = "America/Guadeloupe", CountryId = "GP" };
            yield return new Domain.Entities.TimeZone { Id = "America/Guatemala", CountryId = "GT" };
            yield return new Domain.Entities.TimeZone { Id = "America/Guayaquil", CountryId = "EC" };
            yield return new Domain.Entities.TimeZone { Id = "America/Guyana", CountryId = "GY" };
            yield return new Domain.Entities.TimeZone { Id = "America/Halifax", CountryId = "CA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Havana", CountryId = "CU" };
            yield return new Domain.Entities.TimeZone { Id = "America/Hermosillo", CountryId = "MX" };
            yield return new Domain.Entities.TimeZone { Id = "America/Indiana/Knox", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/Indiana/Marengo", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/Indiana/Petersburg", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/Indiana/Tell_City", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/Indiana/Vevay", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/Indiana/Vincennes", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/Indiana/Winamac", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/Inuvik", CountryId = "CA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Iqaluit", CountryId = "CA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Jamaica", CountryId = "JM" };
            yield return new Domain.Entities.TimeZone { Id = "America/Juneau", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/Kentucky/Monticello", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/Kralendijk", CountryId = "BQ" };
            yield return new Domain.Entities.TimeZone { Id = "America/La_Paz", CountryId = "BO" };
            yield return new Domain.Entities.TimeZone { Id = "America/Lima", CountryId = "PE" };
            yield return new Domain.Entities.TimeZone { Id = "America/Los_Angeles", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/Lower_Princes", CountryId = "SX" };
            yield return new Domain.Entities.TimeZone { Id = "America/Maceio", CountryId = "BR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Managua", CountryId = "NI" };
            yield return new Domain.Entities.TimeZone { Id = "America/Manaus", CountryId = "BR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Marigot", CountryId = "MF" };
            yield return new Domain.Entities.TimeZone { Id = "America/Martinique", CountryId = "MQ" };
            yield return new Domain.Entities.TimeZone { Id = "America/Matamoros", CountryId = "MX" };
            yield return new Domain.Entities.TimeZone { Id = "America/Mazatlan", CountryId = "MX" };
            yield return new Domain.Entities.TimeZone { Id = "America/Menominee", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/Merida", CountryId = "MX" };
            yield return new Domain.Entities.TimeZone { Id = "America/Metlakatla", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/Mexico_City", CountryId = "MX" };
            yield return new Domain.Entities.TimeZone { Id = "America/Miquelon", CountryId = "PM" };
            yield return new Domain.Entities.TimeZone { Id = "America/Moncton", CountryId = "CA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Monterrey", CountryId = "MX" };
            yield return new Domain.Entities.TimeZone { Id = "America/Montevideo", CountryId = "UY" };
            yield return new Domain.Entities.TimeZone { Id = "America/Montserrat", CountryId = "MS" };
            yield return new Domain.Entities.TimeZone { Id = "America/Nassau", CountryId = "BS" };
            yield return new Domain.Entities.TimeZone { Id = "America/New_York", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/Nome", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/Noronha", CountryId = "BR" };
            yield return new Domain.Entities.TimeZone { Id = "America/North_Dakota/Beulah", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/North_Dakota/Center", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/North_Dakota/New_Salem", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/Ojinaga", CountryId = "MX" };
            yield return new Domain.Entities.TimeZone { Id = "America/Panama", CountryId = "PA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Paramaribo", CountryId = "SR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Phoenix", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/Port-au-Prince", CountryId = "HT" };
            yield return new Domain.Entities.TimeZone { Id = "America/Port_of_Spain", CountryId = "TT" };
            yield return new Domain.Entities.TimeZone { Id = "America/Porto_Velho", CountryId = "BR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Puerto_Rico", CountryId = "PR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Punta_Arenas", CountryId = "CL" };
            yield return new Domain.Entities.TimeZone { Id = "America/Rankin_Inlet", CountryId = "CA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Recife", CountryId = "BR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Regina", CountryId = "CA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Resolute", CountryId = "CA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Rio_Branco", CountryId = "BR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Santarem", CountryId = "BR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Santiago", CountryId = "CL" };
            yield return new Domain.Entities.TimeZone { Id = "America/Santo_Domingo", CountryId = "DO" };
            yield return new Domain.Entities.TimeZone { Id = "America/Sao_Paulo", CountryId = "BR" };
            yield return new Domain.Entities.TimeZone { Id = "America/Scoresbysund", CountryId = "GL" };
            yield return new Domain.Entities.TimeZone { Id = "America/Sitka", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "America/St_Barthelemy", CountryId = "BL" };
            yield return new Domain.Entities.TimeZone { Id = "America/St_Johns", CountryId = "CA" };
            yield return new Domain.Entities.TimeZone { Id = "America/St_Kitts", CountryId = "KN" };
            yield return new Domain.Entities.TimeZone { Id = "America/St_Lucia", CountryId = "LC" };
            yield return new Domain.Entities.TimeZone { Id = "America/St_Thomas", CountryId = "VI" };
            yield return new Domain.Entities.TimeZone { Id = "America/St_Vincent", CountryId = "VC" };
            yield return new Domain.Entities.TimeZone { Id = "America/Swift_Current", CountryId = "CA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Tegucigalpa", CountryId = "HN" };
            yield return new Domain.Entities.TimeZone { Id = "America/Thule", CountryId = "GL" };
            yield return new Domain.Entities.TimeZone { Id = "America/Tijuana", CountryId = "MX" };
            yield return new Domain.Entities.TimeZone { Id = "America/Toronto", CountryId = "CA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Tortola", CountryId = "VG" };
            yield return new Domain.Entities.TimeZone { Id = "America/Vancouver", CountryId = "CA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Whitehorse", CountryId = "CA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Winnipeg", CountryId = "CA" };
            yield return new Domain.Entities.TimeZone { Id = "America/Yakutat", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "Antarctica/Casey", CountryId = "AQ" };
            yield return new Domain.Entities.TimeZone { Id = "Antarctica/Davis", CountryId = "AQ" };
            yield return new Domain.Entities.TimeZone { Id = "Antarctica/DumontDUrville", CountryId = "AQ" };
            yield return new Domain.Entities.TimeZone { Id = "Antarctica/Macquarie", CountryId = "AU" };
            yield return new Domain.Entities.TimeZone { Id = "Antarctica/Mawson", CountryId = "AQ" };
            yield return new Domain.Entities.TimeZone { Id = "Antarctica/McMurdo", CountryId = "AQ" };
            yield return new Domain.Entities.TimeZone { Id = "Antarctica/Palmer", CountryId = "AQ" };
            yield return new Domain.Entities.TimeZone { Id = "Antarctica/Rothera", CountryId = "AQ" };
            yield return new Domain.Entities.TimeZone { Id = "Antarctica/Syowa", CountryId = "AQ" };
            yield return new Domain.Entities.TimeZone { Id = "Antarctica/Vostok", CountryId = "AQ" };
            yield return new Domain.Entities.TimeZone { Id = "Arctic/Longyearbyen", CountryId = "SJ" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Aden", CountryId = "YE" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Almaty", CountryId = "KZ" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Amman", CountryId = "JO" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Anadyr", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Aqtau", CountryId = "KZ" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Aqtobe", CountryId = "KZ" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Ashgabat", CountryId = "TM" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Atyrau", CountryId = "KZ" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Baghdad", CountryId = "IQ" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Bahrain", CountryId = "BH" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Baku", CountryId = "AZ" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Bangkok", CountryId = "TH" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Barnaul", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Beirut", CountryId = "LB" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Bishkek", CountryId = "KG" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Brunei", CountryId = "BN" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Chita", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Colombo", CountryId = "LK" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Damascus", CountryId = "SY" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Dhaka", CountryId = "BD" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Dili", CountryId = "TL" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Dubai", CountryId = "AE" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Dushanbe", CountryId = "TJ" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Famagusta", CountryId = "CY" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Gaza", CountryId = "PS" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Hebron", CountryId = "PS" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Hong_Kong", CountryId = "HK" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Hovd", CountryId = "MN" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Irkutsk", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Jakarta", CountryId = "ID" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Jayapura", CountryId = "ID" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Jerusalem", CountryId = "IL" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Kabul", CountryId = "AF" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Kamchatka", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Karachi", CountryId = "PK" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Khandyga", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Krasnoyarsk", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Kuala_Lumpur", CountryId = "MY" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Kuching", CountryId = "MY" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Kuwait", CountryId = "KW" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Macau", CountryId = "MO" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Magadan", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Makassar", CountryId = "ID" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Manila", CountryId = "PH" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Muscat", CountryId = "OM" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Nicosia", CountryId = "CY" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Novokuznetsk", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Novosibirsk", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Omsk", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Oral", CountryId = "KZ" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Phnom_Penh", CountryId = "KH" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Pontianak", CountryId = "ID" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Pyongyang", CountryId = "KP" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Qatar", CountryId = "QA" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Qostanay", CountryId = "KZ" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Qyzylorda", CountryId = "KZ" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Riyadh", CountryId = "SA" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Sakhalin", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Samarkand", CountryId = "UZ" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Seoul", CountryId = "KR" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Shanghai", CountryId = "CN" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Singapore", CountryId = "SG" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Srednekolymsk", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Taipei", CountryId = "TW" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Tashkent", CountryId = "UZ" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Tbilisi", CountryId = "GE" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Tehran", CountryId = "IR" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Thimphu", CountryId = "BT" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Tokyo", CountryId = "JP" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Tomsk", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Ulaanbaatar", CountryId = "MN" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Urumqi", CountryId = "CN" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Ust-Nera", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Vientiane", CountryId = "LA" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Vladivostok", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Yakutsk", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Yekaterinburg", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Asia/Yerevan", CountryId = "AM" };
            yield return new Domain.Entities.TimeZone { Id = "Atlantic/Azores", CountryId = "PT" };
            yield return new Domain.Entities.TimeZone { Id = "Atlantic/Bermuda", CountryId = "BM" };
            yield return new Domain.Entities.TimeZone { Id = "Atlantic/Canary", CountryId = "ES" };
            yield return new Domain.Entities.TimeZone { Id = "Atlantic/Cape_Verde", CountryId = "CV" };
            yield return new Domain.Entities.TimeZone { Id = "Atlantic/Madeira", CountryId = "PT" };
            yield return new Domain.Entities.TimeZone { Id = "Atlantic/Reykjavik", CountryId = "IS" };
            yield return new Domain.Entities.TimeZone { Id = "Atlantic/South_Georgia", CountryId = "GS" };
            yield return new Domain.Entities.TimeZone { Id = "Atlantic/St_Helena", CountryId = "TA" };
            yield return new Domain.Entities.TimeZone { Id = "Atlantic/Stanley", CountryId = "FK" };
            yield return new Domain.Entities.TimeZone { Id = "Australia/Adelaide", CountryId = "AU" };
            yield return new Domain.Entities.TimeZone { Id = "Australia/Brisbane", CountryId = "AU" };
            yield return new Domain.Entities.TimeZone { Id = "Australia/Broken_Hill", CountryId = "AU" };
            yield return new Domain.Entities.TimeZone { Id = "Australia/Darwin", CountryId = "AU" };
            yield return new Domain.Entities.TimeZone { Id = "Australia/Eucla", CountryId = "AU" };
            yield return new Domain.Entities.TimeZone { Id = "Australia/Hobart", CountryId = "AU" };
            yield return new Domain.Entities.TimeZone { Id = "Australia/Lindeman", CountryId = "AU" };
            yield return new Domain.Entities.TimeZone { Id = "Australia/Lord_Howe", CountryId = "AU" };
            yield return new Domain.Entities.TimeZone { Id = "Australia/Melbourne", CountryId = "AU" };
            yield return new Domain.Entities.TimeZone { Id = "Australia/Perth", CountryId = "AU" };
            yield return new Domain.Entities.TimeZone { Id = "Australia/Sydney", CountryId = "AU" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Amsterdam", CountryId = "NL" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Andorra", CountryId = "AD" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Astrakhan", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Athens", CountryId = "GR" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Belgrade", CountryId = "RS" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Berlin", CountryId = "DE" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Bratislava", CountryId = "SK" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Brussels", CountryId = "BE" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Bucharest", CountryId = "RO" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Budapest", CountryId = "HU" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Busingen", CountryId = "DE" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Chisinau", CountryId = "MD" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Copenhagen", CountryId = "DK" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Dublin", CountryId = "IE" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Gibraltar", CountryId = "GI" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Guernsey", CountryId = "GG" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Helsinki", CountryId = "FI" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Isle_of_Man", CountryId = "IM" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Istanbul", CountryId = "TR" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Jersey", CountryId = "JE" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Kaliningrad", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Kirov", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Lisbon", CountryId = "PT" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Ljubljana", CountryId = "SI" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/London", CountryId = "GB" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Luxembourg", CountryId = "LU" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Madrid", CountryId = "ES" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Malta", CountryId = "MT" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Mariehamn", CountryId = "AX" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Minsk", CountryId = "BY" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Monaco", CountryId = "MC" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Moscow", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Oslo", CountryId = "NO" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Paris", CountryId = "FR" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Podgorica", CountryId = "ME" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Prague", CountryId = "CZ" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Riga", CountryId = "LV" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Rome", CountryId = "IT" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Samara", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/San_Marino", CountryId = "SM" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Sarajevo", CountryId = "BA" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Saratov", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Simferopol", CountryId = "UA" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Skopje", CountryId = "MK" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Sofia", CountryId = "BG" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Stockholm", CountryId = "SE" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Tallinn", CountryId = "EE" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Tirane", CountryId = "AL" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Ulyanovsk", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Vaduz", CountryId = "LI" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Vatican", CountryId = "VA" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Vienna", CountryId = "AT" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Vilnius", CountryId = "LT" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Volgograd", CountryId = "RU" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Warsaw", CountryId = "PL" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Zagreb", CountryId = "HR" };
            yield return new Domain.Entities.TimeZone { Id = "Europe/Zurich", CountryId = "CH" };
            yield return new Domain.Entities.TimeZone { Id = "Indian/Antananarivo", CountryId = "MG" };
            yield return new Domain.Entities.TimeZone { Id = "Indian/Chagos", CountryId = "DG" };
            yield return new Domain.Entities.TimeZone { Id = "Indian/Christmas", CountryId = "CX" };
            yield return new Domain.Entities.TimeZone { Id = "Indian/Cocos", CountryId = "CC" };
            yield return new Domain.Entities.TimeZone { Id = "Indian/Comoro", CountryId = "KM" };
            yield return new Domain.Entities.TimeZone { Id = "Indian/Kerguelen", CountryId = "TF" };
            yield return new Domain.Entities.TimeZone { Id = "Indian/Mahe", CountryId = "SC" };
            yield return new Domain.Entities.TimeZone { Id = "Indian/Maldives", CountryId = "MV" };
            yield return new Domain.Entities.TimeZone { Id = "Indian/Mauritius", CountryId = "MU" };
            yield return new Domain.Entities.TimeZone { Id = "Indian/Mayotte", CountryId = "YT" };
            yield return new Domain.Entities.TimeZone { Id = "Indian/Reunion", CountryId = "RE" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Apia", CountryId = "WS" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Auckland", CountryId = "NZ" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Bougainville", CountryId = "PG" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Chatham", CountryId = "NZ" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Easter", CountryId = "CL" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Efate", CountryId = "VU" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Fakaofo", CountryId = "TK" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Fiji", CountryId = "FJ" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Funafuti", CountryId = "TV" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Galapagos", CountryId = "EC" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Gambier", CountryId = "PF" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Guadalcanal", CountryId = "SB" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Guam", CountryId = "GU" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Honolulu", CountryId = "US" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Kiritimati", CountryId = "KI" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Kosrae", CountryId = "FM" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Kwajalein", CountryId = "MH" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Majuro", CountryId = "MH" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Marquesas", CountryId = "PF" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Midway", CountryId = "UM" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Nauru", CountryId = "NR" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Niue", CountryId = "NU" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Norfolk", CountryId = "NF" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Noumea", CountryId = "NC" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Pago_Pago", CountryId = "AS" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Palau", CountryId = "PW" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Pitcairn", CountryId = "PN" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Port_Moresby", CountryId = "PG" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Rarotonga", CountryId = "CK" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Saipan", CountryId = "MP" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Tahiti", CountryId = "PF" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Tarawa", CountryId = "KI" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Tongatapu", CountryId = "TO" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Wake", CountryId = "UM" };
            yield return new Domain.Entities.TimeZone { Id = "Pacific/Wallis", CountryId = "WF" };
        }
    }
}

